package com.numble;

import com.numble.model.Colour;
import com.numble.model.Mode;
import java.util.List;

public interface GameInterface {

  /**
   * method to check the user's guess
   * @param userGuess the user guess
   * @return arraylist containing the colour of each tile
   */
  List<Colour> checkGuess(List<String> userGuess);

  /**
   * method to check if the user has won or not
   * @return true if the user has won
   */
  boolean hasWon();

  /**
   * method to check if the user has lost or not
   * @return true if the user has lost (i.e. no guesses remaining and game not won)
   */
  boolean hasLost();

  /**
   * method to return the equation which the user must guess.
   * This equation ("target") has been generated by generateEquation.
   * @return string equation to guess.
   */
  String getTarget();

  /**
   * method to get the result (i.e. answer) of the equation
   * @return string result of equation
   */
  String getTargetResult();

  Mode getGameMode();
}
